### ISSUE TITLE
Kotlin DSL Example

### ISSUE THREAD

**Issue by garethpowell** [edeandrea/xjc-generation-gradle-plugin#17] opened 2020-03-16 16:44 UTC
Could you please provide a working example of how this is configured when using Kotlin DSL for the Gradle file?

**Comment by edeandrea** [comment] 2020-03-18 13:30
Hi @garethpowell thanks for the interest in this project & sorry about the delay in getting back to you about this.

I've added some samples to the main readme for configuration using the Kotlin DSL.

Let me know if there's anything else you need. I'm going to close this issue for now but feel free to re-open if you need anything else related to this.

**Closed as completed** 2020-03-18 13:31 UTC
Labels: documentation

**Comment by garethpowell** [comment] 2020-03-19 15:47
Hi @edeandrea,

Many thanks for your prompt response. I'm busy building Kotlin/SpringBoot/Gradle based apps, but sadly still bound to consuming legacy SOAP APIs, so finding this plugin was great. I've now got the plugin working with your help. :-) 

May I suggest you also add the following to the docs as well so that generated sources are included correctly in the build.
`sourceSets {`
    `named("main") {`
		`java {`
			`srcDirs("${buildDir}/generated-sources/main/xjc/")`
		`}`
	`}`
`}`

Or better still, get the plugin to do it.

Best regards and thanks again

Gareth

**Comment by edeandrea** [comment] 2020-03-19 15:51
Hi @garethpowell awesome! This plugin was really born out of my own frustrations with similar situations and no other plugins working exactly the way I wanted.

The sources should already be included in the build (https://github.com/edeandrea/xjc-generation-gradle-plugin/blob/1a2cc006f142ea7f7e587fc52634bf7e2a202801/src/main/kotlin/com/github/edeandrea/xjcplugin/plugin/XjcPlugin.kt#L102). It also works fine in my unit & integration tests. Are you seeing different behavior?

**Comment by garethpowell** [comment] 2020-03-19 16:04
Yeah, I am. It just doesn't resolve. I've just done a quick test, and it would appear to be because my application code is all Kotlin. When I build just Java source the generated sources resolve correctly.

**Comment by edeandrea** [comment] 2020-03-19 16:20
If thats the case then how does adding

```kotlin
sourceSets {
  named("main") {
    java {
      srcDirs("${buildDir}/generated-sources/main/xjc/")
    }
  }
}
```

fix that? That is exactly the same thing the plugin is doing.

**Comment by edeandrea** [comment] 2020-03-19 16:38
Wait I know what the issue is. I've opened #18 for this.
